-- Seed website content from current website (FAQs, amenities, Why Us).
-- Run once after 001, 002, 003. If tables already have data, skip or truncate first.
-- Does NOT modify any portal tables.

-- ============================================
-- 1. SEED website_faqs (only when empty)
-- ============================================
DO $$
DECLARE
  faq_count integer;
BEGIN
  SELECT COUNT(*) INTO faq_count FROM website_faqs;
  IF faq_count = 0 THEN
    INSERT INTO website_faqs (question, answer, category, display_order, is_active) VALUES
    ('What are the different studio sizes available?', E'We offer a range of studio sizes to suit your needs:\n\nSilver: 19 – 20 m²\nGold: 22 – 23 m²\nPlatinum: 25 – 26 m²\nRhodium: 28 – 30 m²\nRhodium Plus: 40 – 42 m²', 'Booking & Tenancy', 0, true),
    ('Do I have to pay a booking fee?', E'No, we do not charge a booking fee. However, you may be required to pay a deposit to secure your room, which is refundable under certain conditions.', 'Booking & Tenancy', 1, true),
    ('Can I apply for Dual Occupancy?', E'Dual occupancy is available on most rooms over 23sqm. Both occupants would need to apply and mention in their application that they are applying for dual occupancy so that the price can be amended. The price would be the total rent plus an additional £80 and then divided by two for each occupant''s weekly cost unless otherwise stated.', 'Booking & Tenancy', 2, true),
    ('What if I want to cancel my booking?', E'You can cancel your tenancy agreement for up to 7 days after the date of your booking (the Initial Cancellation Period).\n\nWe will refund the security deposit. An administrative fee of £10 will be deducted from any deposit refunded to UK bank accounts. For refunds made to non-UK bank accounts, an administrative fee plus applicable bank charges, totalling £20, will be deducted from the refund amount.\n\nIf you wish to cancel your tenancy agreement after the initial cancellation period or after your tenancy has started, you will be responsible for paying the rent and any applicable fees for the full tenancy period. However, if you find a replacement tenant who is approved by the landlord and has paid both the deposit and rent, your liability will be limited to the time until the replacement tenant takes over payment. The tenancy termination will only be confirmed once the replacement tenant has completed these payments.\n\nIf a replacement tenant is found, there will be a £50 fee for updating the contract, which you will need to pay within 14 days, or it will be taken from your deposit. Once the new tenancy begins, the landlord will release you from your tenancy agreement.', 'Booking & Tenancy', 3, true),
    ('Can I request to move rooms during my tenancy?', 'Yes, you can request to move rooms. However, this is subject to availability and may incur additional charges. Please reach out to the accommodation team for assistance.', 'Booking & Tenancy', 4, true),
    ('Do I have to move out during holidays?', 'No, you do not have to move out during holidays. Your tenancy agreement covers the full contract period, and you have access to your room throughout the academic year, including holiday periods.', 'Booking & Tenancy', 5, true),
    ('Can I move in before my contract starts?', E'If you wish to arrive earlier than your contract start date, you need to email or call the site office. If early arrival is possible your contract will be adjusted, and you will need to accept it then pay the additional charges prior to arrival. Please note, not all requests can be accommodated.', 'Booking & Tenancy', 6, true),
    ('How do you allocate rooms?', E'When applying for a room you will be asked a series of questions to determine the type of room/flat that you require, along with any special requests you may have. Please note that special requests cannot be guaranteed except where you have disability as defined and covered under the Equality Act 2010. We will attempt to meet your allocation needs as far as practicably possible, should you have a defined disability.\n\nIf you have a disability, medical condition or special request that affects your accommodation requirement please inform us in the additional notes section when completing your application, either online or by paper form.\n\nYou are encouraged to disclose any special requests for your stay such as your preferences regarding culture, religion, sex, gender, etc. to enable us to make an informed decision about your room allocation. Where appropriate, an applicant may be prioritised through the allocation categories as a result of disclosing a disability to us.', 'Booking & Tenancy', 7, true),
    ('Do I need a guarantor?', 'If you wish to pay your rent in instalments, you will need a UK guarantor.', 'Payments & Rent', 8, true),
    ('Who can be a guarantor?', E'To be a guarantor you must:\n\n• Be resident in the UK for a minimum of 1 year\n• Be over 21 years of age\n• Be a homeowner or in full time employment\n• Provide a copy of photographic identification, such as a passport, driving licence or ID badge\n• Provide a copy of proof of your UK address which must be less than 3 months old, such as a utility bill (e.g. electricity, water, gas, telephone), a bank statement or a Council Tax bill.', 'Payments & Rent', 9, true),
    ('When do I pay my rent?', E'If you have a valid UK Guarantor, you can choose to pay your rent in three instalments, which are due in September, January, and April.\n\nIf you don''t have a valid UK Guarantor, you are required to pay the full rent in August, 1 month prior to your contract start date.\n\nPlease note you must have paid the rent due by the time you arrive to check in.\n\nOther instalment options may be available.', 'Payments & Rent', 10, true),
    (E'What''s included in my rent?', E'All utility bills such as electricity, water are included in your rent. Unlimited Wi-fi* is also included. Your TV licence is not included in your rent as this is not classed as a utility and is your responsibility to purchase.\n\nUrban Hub offer a Wi-fi connection at the stated level** included within the rent and there is no additional charge for use of the on-site internet.\n\nFor information on the speed of your internet connection, please ask your Property Team for more information.\n\n** the internet speed is the maximum stated speed available into the property.', 'Payments & Rent', 11, true),
    ('Can I pay my rent in instalments?', E'Yes, we offer flexible payment plans, including instalment options. The number of instalments depends on the length of your contract and whether you have a guarantor.', 'Payments & Rent', 12, true),
    ('What can I do if my student loan has not arrived yet?', E'You can defer your rent instalments to be in line with your student loan payments if you wish. All requests for deferred payments must be made by 1st August in each academic year to the property team.\n\nYou will be required to provide evidence of your student loan schedule to the property team in order for the payment plan to be set up.\n\nYou will be required to pay two weeks rent 14 days prior to your contract start date, which will be deducted from the balance of your first instalment on the agreed date.\n\nA one-off admin fee of £50 will be charge and payable with the initial 2 week rent payment and this £50 admin fee will not be deducted from the balance of rent due.\n\nPlease note deferring your rent must be pre-arranged and agreed with the property manager prior to your move in date. If no arrangement has been made, rent is due as per your tenancy agreement.', 'Payments & Rent', 13, true),
    ('What do I do if I''m a first-year student and I''m still awaiting my exam results?', E'If you are still waiting for your exam results and you are not sure whether your place at university is confirmed, do not worry, you can still apply.\n\nIf you are a prospective first year Undergraduate or Postgraduate student and your offer of a place at your preferred University or Higher Education Institute is withdrawn by the University or Higher Education Institute because you do not achieve the required entry grades, you may be eligible to be released from this agreement.\n\nYou must provide written evidence from the University that you do not have a place within 3 days of your results being published (and no later than 28th August, whichever date is sooner) and we will release you from the contract without penalty and refund the deposit paid.\n\nYou may also be eligible to be released from this agreement if you are a prospective first year Undergraduate student and you choose to go to a different University because you have exceeded your expected grades.\n\nTo apply to be released from this agreement in the circumstances referred to above, you will need to supply us with a copy of:\n\n• A written or email confirmation that you wish to cancel your reservation, stating full name and full details of the property booked;\n• A written rejection letter from your chosen university/college or UCAS, a screen shot of your UCAS status which confirms that the required results were not achieved, or a copy of the proof of acceptance of your new university by UCAS adjustment.\n\nThese document(s) must be received by us within 3 calendar days from the date your results are published. On receipt of the required documentation, it will be verified and, provided we are satisfied, we will cancel your agreement and refund your deposit in full.', 'Admissions & Cancellations', 14, true),
    ('What do I do if I''m a first-year postgraduate student and I''m still awaiting my exam results?', E'If you are a prospective first year Postgraduate student and your offer of a place at your preferred University or Higher Education Institute is withdrawn by the University or Higher Education Institute because you do not achieve the required entry grades, you may be eligible to be released from this agreement.\n\nYou must provide written evidence from the University that you do not have a place within 3 days of your results being published (and no later than 28th August, whichever date is sooner) and we will release you from the contract without penalty and refund the deposit paid.\n\nTo apply to be released from this agreement, you will need to supply us with a copy of:\n\n• A written or email confirmation that you wish to cancel your reservation, stating full name and full details of the property booked;\n• A written rejection letter from your chosen university/college confirming that the required results were not achieved.\n\nThese document(s) must be received by us within 3 calendar days from the date your results are published. On receipt of the required documentation, it will be verified and, provided we are satisfied, we will cancel your agreement and refund your deposit in full.', 'Admissions & Cancellations', 15, true),
    ('Does my rental include room cleaning?', E'No, room cleaning is not included in the rent. However, communal areas may be cleaned regularly. You are responsible for keeping your personal space tidy.', 'Accommodation & Facilities', 16, true),
    ('What can I bring?', E'You can bring most of your belongings but some electricals aren''t suitable for our properties. Non-UK compliant electricals such as rice cookers are not suitable for use with UK power outlets and this can cause fire risks.', 'Accommodation & Facilities', 17, true),
    ('Are pets allowed?', 'No, pets are not allowed in our accommodation, except for registered assistance animals.', 'Accommodation & Facilities', 18, true),
    ('Fraudulent Activity', E'It is known that people or businesses make bookings of rooms in high demand properties and cities to sell to individuals later, or pay others to make bookings to be resold later. While we do everything we can to stop this fraudulent activity, including requiring ID and university evidence, it is not possible to stop it completely. The individuals and groups conducting this fraudulent activity claim to have legitimate reasons to want to sell their rooms, but subsequently charge high additional fees to the genuine student who wants the room.\n\nStudents should NOT book rooms from private individuals claiming to have special offers or exclusivity of rooms. We manage enquiries, bookings, and organise tenancy takeovers directly. It is highly unlikely a room that becomes unwanted by an individual will be re-let to a student who is introduced to us by that person.\n\nIf in any doubt as to the legitimacy of a room offer, special promotion, or to verify if an individual or business advertising rooms to let is legitimate, you should NOT make any payment to them, and contact the reception team.', 'Policies & Regulations', 19, true),
    ('Recycling', E'Recycling is one of the best ways for you to have a positive impact on the world in which we live. Recycling is important to both the natural environment and us. We must act fast as the amount of waste we create is increasing all the time.\n\nAt the Urban Hub we want to do our bit to protect the world, and we''re sure you want to do your bit too, so to make being eco-friendly easy for you we''ve provided recycling and refuse bins throughout your accommodation and we encourage all students to use the facilities provided to recycle waste where possible.\n\nYou should make sure that you empty packages completely and give them a quick rinse before you recycle them. Below you can find examples of what you can recycle and what goes in the different bins.\n\nBe aware that if you put things in the wrong bin, it will contaminate the whole waste load which means that we cannot send that waste to be recycled. So, please take an extra couple of seconds to put things in the correct bin so we can help divert as much waste from going to landfill as possible.\n\nAlmost anything made of glass can be recycled, so make sure you put items like glass bottles and jars in the right bin and do not recycle broken glass or light bulbs. Anything that does not feature a recycling label must be put in the refuse bin. Other items that are not recyclable include: batteries, electrical appliances, kitchen waste, polystyrene, foam and sanitary products.', 'Policies & Regulations', 20, true),
    ('Do I need to pay council tax?', E'Full-time students are exempt from council tax. However, if you are a part-time student or not studying, you may be responsible for council tax payments. Contact your local council for more information.', 'Policies & Regulations', 21, true),
    ('What if I have a complaint?', 'If you have a complaint this will need to be sent in writing to the property manager who then has 7 working days to respond.', 'Policies & Regulations', 22, true);
  END IF;
END $$;

-- ============================================
-- 2. SEED website_amenities (only when empty)
-- ============================================
DO $$
DECLARE
  amenity_count integer;
BEGIN
  SELECT COUNT(*) INTO amenity_count FROM website_amenities;
  IF amenity_count = 0 THEN
    INSERT INTO website_amenities (title, short_description, vertical_image_url, horizontal_image_url, display_order, is_active) VALUES
    ('Chill Spot', NULL, NULL, NULL, 0, true),
    ('Chill Zone', NULL, NULL, NULL, 1, true),
    ('Equipped Gym', NULL, NULL, NULL, 2, true),
    ('Game Room', NULL, NULL, NULL, 3, true),
    ('Game Room 2', NULL, NULL, NULL, 4, true),
    ('Student Lounge', NULL, NULL, NULL, 5, true),
    ('Exterior Side Shot', NULL, NULL, NULL, 6, true),
    ('Aerial Shot', NULL, NULL, NULL, 7, true);
  END IF;
END $$;

-- ============================================
-- 3. SEED website_why_us_cards (only when empty)
-- ============================================
DO $$
DECLARE
  why_count integer;
BEGIN
  SELECT COUNT(*) INTO why_count FROM website_why_us_cards;
  IF why_count = 0 THEN
    INSERT INTO website_why_us_cards (title, description, icon, icon_url, display_order, is_active) VALUES
    ('Preston''s Most Advanced Student Hub', 'The biggest, boldest upgrade to student life in the city.', NULL, NULL, 0, true),
    ('Your Own City Apartment', 'Live independently while surrounded by like-minded people and lifestyle-driven spaces.', NULL, NULL, 1, true),
    ('Tesco Express Right Downstairs', 'Everyday essentials just seconds away convenience at your doorstep.', NULL, NULL, 2, true),
    ('All-in-one Living with 10+ Lifestyle Zones', 'Gym, cinema, rooftop terrace, chill lounges, study zones all under one roof.', NULL, NULL, 3, true),
    ('Exclusive Rooftop Terrace For Residents Only', 'The only student property in Preston with private rooftop access and skyline views.', NULL, NULL, 4, true),
    ('Trusted by 400+ Students Every Year', 'The go-to choice for students who want more than just a place to sleep.', NULL, NULL, 5, true),
    ('Designed with a Modern Touch', 'Every space features sleek, high-quality furnishings and contemporary design.', NULL, NULL, 6, true),
    ('Fitness-Focused Living', 'Train just steps from your room wellness and motivation built in.', NULL, NULL, 7, true);
  END IF;
END $$;
