-- Seed seo_pages with all website pages and recommended SEO (title, description, focus keyphrase, OG, Twitter, canonical, robots).
-- Uses ON CONFLICT DO NOTHING so existing rows are not overwritten; you can edit later.
-- Run after 001–005. Does NOT modify portal tables.

INSERT INTO seo_pages (
  page_path, page_type, meta_title, meta_description, focus_keyword, canonical_url,
  og_title, og_description, og_image_url, twitter_title, twitter_description, twitter_image_url, robots_meta
)
VALUES
  ('/', 'page',
   'Urban Hub Student Accommodation Preston | Studios & Apartments',
   'Book your student studio in Preston. Urban Hub offers modern studios, 10+ lifestyle zones, rooftop terrace and Tesco Express on site. View availability and prices.',
   'student accommodation Preston', NULL,
   'Urban Hub Student Accommodation Preston | Studios & Apartments',
   'Book your student studio in Preston. Modern studios, 10+ lifestyle zones, rooftop terrace. View availability and prices.',
   NULL, 'Urban Hub Student Accommodation Preston | Studios & Apartments',
   'Book your student studio in Preston. Modern studios, 10+ lifestyle zones, rooftop terrace.', NULL,
   'index, follow'),
  ('/studios', 'page',
   'Studios & Room Types | Urban Hub Student Accommodation Preston',
   'Explore studio types at Urban Hub Preston: Silver, Gold, Platinum, Rhodium and Rhodium Plus. Compare sizes, prices and book your room for the academic year.',
   'student studios Preston', NULL,
   'Studios & Room Types | Urban Hub Student Accommodation Preston',
   'Explore studio types: Silver, Gold, Platinum, Rhodium and Rhodium Plus. Compare sizes and prices.',
   NULL, 'Studios & Room Types | Urban Hub Preston',
   'Explore studio types: Silver, Gold, Platinum, Rhodium and Rhodium Plus.', NULL,
   'index, follow'),
  ('/contact', 'page',
   'Contact Us | Urban Hub Student Accommodation Preston',
   'Get in touch with Urban Hub Preston. Contact us for enquiries, viewings and support. We are here to help with your student accommodation.',
   'contact Urban Hub Preston', NULL,
   'Contact Us | Urban Hub Student Accommodation Preston',
   'Get in touch for enquiries, viewings and support. We are here to help.',
   NULL, 'Contact Us | Urban Hub Preston', 'Get in touch for enquiries, viewings and support.', NULL,
   'index, follow'),
  ('/faq', 'page',
   'FAQ | Urban Hub Student Accommodation Preston',
   'Frequently asked questions about booking, rent, guarantors, cancellations and facilities at Urban Hub student accommodation Preston.',
   'student accommodation FAQ Preston', NULL,
   'FAQ | Urban Hub Student Accommodation Preston',
   'FAQs about booking, rent, guarantors, cancellations and facilities.',
   NULL, 'FAQ | Urban Hub Preston', 'FAQs about booking, rent, guarantors and facilities.', NULL,
   'index, follow'),
  ('/blog', 'page',
   'Blog | Urban Hub Student Accommodation Preston',
   'News, tips and updates from Urban Hub student accommodation in Preston. Student life, moving in and local guides.',
   'student accommodation blog Preston', NULL,
   'Blog | Urban Hub Student Accommodation Preston',
   'News, tips and updates from Urban Hub student accommodation in Preston.',
   NULL, 'Blog | Urban Hub Preston', 'News, tips and updates from Urban Hub.', NULL,
   'index, follow'),
  ('/about', 'page',
   'About Us | Urban Hub Student Accommodation Preston',
   'Learn about Urban Hub Preston: modern student accommodation with gym, cinema, rooftop terrace and 10+ lifestyle zones. Trusted by 400+ students every year.',
   'about Urban Hub Preston', NULL,
   'About Us | Urban Hub Student Accommodation Preston',
   'Modern student accommodation with gym, cinema, rooftop terrace. Trusted by 400+ students.',
   NULL, 'About Us | Urban Hub Preston', 'Modern student accommodation. Trusted by 400+ students.', NULL,
   'index, follow'),
  ('/short-term', 'page',
   'Short Term Stays | Urban Hub Student Accommodation Preston',
   'Book short-term student accommodation in Preston. Flexible stays for tourists and key workers. Check availability and rates.',
   'short term student accommodation Preston', NULL,
   'Short Term Stays | Urban Hub Student Accommodation Preston',
   'Flexible short-term stays in Preston for tourists and key workers.',
   NULL, 'Short Term Stays | Urban Hub Preston', 'Flexible short-term stays in Preston.', NULL,
   'index, follow'),
  ('/privacy', 'page',
   'Privacy Policy | Urban Hub Student Accommodation Preston',
   'Privacy policy for Urban Hub student accommodation Preston. How we collect, use and protect your personal data.',
   'privacy policy Urban Hub', NULL,
   'Privacy Policy | Urban Hub Student Accommodation Preston',
   'How we collect, use and protect your personal data.',
   NULL, 'Privacy Policy | Urban Hub Preston', 'How we collect, use and protect your data.', NULL,
   'index, follow'),
  ('/terms', 'page',
   'Terms & Conditions | Urban Hub Student Accommodation Preston',
   'Terms and conditions for Urban Hub student accommodation Preston. Booking, tenancy and site use.',
   'terms and conditions Urban Hub', NULL,
   'Terms & Conditions | Urban Hub Student Accommodation Preston',
   'Terms and conditions for booking, tenancy and site use.',
   NULL, 'Terms & Conditions | Urban Hub Preston', 'Terms for booking, tenancy and site use.', NULL,
   'index, follow'),
  ('/reviews', 'page',
   'Reviews | Urban Hub Student Accommodation Preston',
   'Read student reviews of Urban Hub Preston. See what residents say about our studios, facilities and community.',
   'Urban Hub reviews Preston', NULL,
   'Reviews | Urban Hub Student Accommodation Preston',
   'Read student reviews and testimonials from Urban Hub Preston residents.',
   NULL, 'Reviews | Urban Hub Preston', 'Read student reviews and testimonials.', NULL,
   'index, follow')
ON CONFLICT (page_path) DO NOTHING;
